compile:
	g++ Retirement.cpp -c
	g++ Register.cpp -c
	g++ Loan.cpp -c
	g++ Clementine.cpp -c
	g++ Clementine.o Retirement.o Loan.o Register.o -o infinity.out
clean:
	rm *.o 
compile2:
	g++ -o infinity2.out Register.cpp Retirement.cpp Loan.cpp Clementine.cpp -I.
